name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  HUSKY: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn lint --fix
      - run: yarn prettier
      - run: yarn build
      - name: correct vercel/ncc crlf output
        run: sed -i 's/\x0D$//' ./dist/index.js
      - name: check for unstaged files
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: .github/no-unstaged-files.sh
